config/routes.rb
# encoding: UTF-8

# Copyright 2011-2013 innoQ Deutschland GmbH
#
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Rails.application.routes.draw do
  apipie

  scope ':lang', constraints: Iqvoc.routing_constraint do
    Iqvoc.localized_routes.each do |hook|
      hook.call(self)
      ActiveSupport::Deprecation.warn <<-EOF
        Adding routes via `Iqvoc.localized_routes` is deprecated and will
        be removed in iQvoc 4.5.
      EOF
    end

    resource  :user_session, only: [:new, :create, :destroy]
    resources :users, except: [:show]
    resources :concepts do
      member do
        get 'glance'
      end
    end
    resources :collections
    resources :imports, only: [:index, :show, :create]
    resources :exports, only: [:index, :show, :create] do
      get 'download'
    end

    get 'scheme' => 'concepts/scheme#show', as: 'scheme'
    get 'scheme/edit' => 'concepts/scheme#edit', as: 'edit_scheme'
    patch 'scheme' => 'concepts/scheme#update'

    get 'hierarchy' => 'hierarchy#index'
    get 'hierarchy/:root' => 'hierarchy#show'

    get 'triplestore_sync' => 'triplestore_sync#index'
    post 'triplestore_sync' => 'triplestore_sync#sync'

    post 'concepts/:origin/branch'      => 'concepts/versions#branch',    as: 'concept_versions_branch'
    post 'concepts/:origin/merge'       => 'concepts/versions#merge',     as: 'concept_versions_merge'
    post 'concepts/:origin/lock'        => 'concepts/versions#lock',      as: 'concept_versions_lock'
    post 'concepts/:origin/unlock'      => 'concepts/versions#unlock',    as: 'concept_versions_unlock'
    post 'concepts/:origin/to_review'   => 'concepts/versions#to_review', as: 'concept_versions_to_review'
    get 'concepts/:origin/consistency_check' => 'concepts/versions#consistency_check', as: 'concept_versions_consistency_check'

    patch 'concepts/:origin/move'        => 'concepts_movement#move',     as: 'move_concept'

    post 'collections/:origin/branch'      => 'collections/versions#branch',    as: 'collection_versions_branch'
    post 'collections/:origin/merge'       => 'collections/versions#merge',     as: 'collection_versions_merge'
    post 'collections/:origin/lock'        => 'collections/versions#lock',      as: 'collection_versions_lock'
    post 'collections/:origin/unlock'      => 'collections/versions#unlock',    as: 'collection_versions_unlock'
    post 'collections/:origin/to_review'   => 'collections/versions#to_review', as: 'collection_versions_to_review'
    get 'collections/:origin/consistency_check' => 'collections/versions#consistency_check', as: 'collection_versions_consistency_check'

    get 'alphabetical_concepts(/:prefix)' => 'concepts/alphabetical#index', as: 'alphabetical_concepts'
    get 'untranslated_concepts/:prefix'   => 'concepts/untranslated#index', as: 'untranslated_concepts'
    get 'hierarchical_concepts' => 'concepts/hierarchical#index', as: 'hierarchical_concepts'
    get 'expired_concepts' => 'concepts/expired#index', as: 'expired_concepts'

    get 'dashboard' => 'dashboard#concept_index', as: 'dashboard'
    get 'dashboard_glance' => 'dashboard#glance', as: 'dashboard_glance'
    get 'collection_dashboard' => 'dashboard#collection_index', as: 'collection_dashboard'
    match 'dashboard/reset' => 'dashboard#reset', as: 'reset', via: [:get, :post]

    get 'config' => 'instance_configuration#index', as: 'instance_configuration'
    patch 'config' => 'instance_configuration#update'

    get 'search' => 'search_results#index', as: 'search'

    get 'help' => 'pages#help', as: 'help'
    get 'version' => 'pages#version', as: 'version'
    get 'components' => 'pages#components', as: 'components'

    get '/' => 'frontpage#index', as: 'localized_root'
    match '*unmatched', to: 'errors#not_found', via: :all
  end

  patch ':origin/add_match' => 'reverse_matches#add_match', as: 'add_match'
  patch ':origin/remove_match' => 'reverse_matches#remove_match', as: 'remove_match'

  get 'remote_labels' => 'remote_labels#show', as: 'remote_label'
  get 'schema' => redirect('/'), as: 'schema'
  get 'dataset' => 'rdf#dataset', as: 'rdf_dataset'
  get 'scheme' => 'concepts/scheme#show', as: 'rdf_scheme'
  get 'search' => 'search_results#index', as: 'rdf_search'
  get 'hierarchy' => 'hierarchy#index'
  get 'hierarchy/:root' => 'hierarchy#show'

  get ':id' => 'rdf#show', as: 'rdf'

  match '*unmatched', to: 'errors#not_found', via: :all

  root to: 'frontpage#index', format: nil
end

app/models/collection/member/base.rb
# encoding: UTF-8

# Copyright 2011-2013 innoQ Deutschland GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class Collection::Member::Base < ApplicationRecord
  self.table_name = 'collection_members'

  class_attribute :rdf_namespace, :rdf_predicate
  self.rdf_namespace = nil
  self.rdf_predicate = nil

  belongs_to :collection,
             class_name: 'Collection::Base'

  belongs_to :target,
             class_name: 'Concept::Base'

  def self.view_section(obj)
    'main'
  end

  def self.view_section_sort_key(obj)
    100
  end

  def self.partial_name(obj)
    'partials/collection/member'
  end
end

app/models/collection/member/skos/base.rb
# encoding: UTF-8

# Copyright 2012 Hola, S.L.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class Collection::Member::SKOS::Base < Collection::Member::Base
  self.rdf_namespace = 'skos'
  self.rdf_predicate = 'member'

  def self.build_from_rdf(rdf_subject, rdf_predicate, rdf_object)
    raise "#{self.name}#build_from_rdf: Subject (#{rdf_subject}) must be a Collection."          unless rdf_subject.is_a?(Collection::Base)
    raise "#{self.name}#build_from_rdf: Object (#{rdf_object}) must be a Collection or Concept." unless rdf_object.is_a?(Collection::Base) or rdf_object.is_a?(Concept::Base)

    member_instance = rdf_subject.members.detect{ |rel| rel.target == rdf_object }
    if member_instance.nil?
      predicate_class = RDFAPI::PREDICATE_DICTIONARY[rdf_predicate] || self
      member_instance = predicate_class.new(target: rdf_object)
      rdf_subject.members << member_instance
    end

    if rdf_object.collections.select{ |coll| coll.id == rdf_subject.id }.empty?
      rdf_object.collections << rdf_subject
    end
    member_instance
  end
end

app/controllers/collections/versions_controller.rb
# encoding: UTF-8

# Copyright 2011-2013 innoQ Deutschland GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class Collections::VersionsController < ApplicationController
  include RDFSyncService::Helper

  def merge
    scope = Iqvoc::Collection.base_class.by_origin(params[:origin])

    current_collection = scope.published.last
    new_version = scope.unpublished.last!

    authorize! :merge, new_version

    ActiveRecord::Base.transaction do
      new_version.rdf_updated_at = nil
      new_version.publish
      new_version.unlock
      if new_version.publishable?
        new_version.save

        if current_collection && !current_collection.destroy
          flash[:error] = t('txt.controllers.versioning.merged_delete_error')
          redirect_to collection_path(new_version, published: 0)
        end

        if Iqvoc.config['triplestore.autosync']
          synced = triplestore_syncer.sync([new_version]) # XXX: blocking
          flash[:warning] = 'triplestore synchronization failed' unless synced # TODO: i18n
        end

        flash[:success] = t('txt.controllers.versioning.published')
        redirect_to collection_path(new_version)
      else
        flash[:error] = t('txt.controllers.versioning.merged_publishing_error')
        redirect_to collection_path(new_version, published: 0)
      end
    end
  end

  def branch
    scope = Iqvoc::Collection.base_class.by_origin(params[:origin])
    current_collection = scope.published.last!

    if draft_collection = scope.unpublished.last
      flash[:info] = t('txt.controllers.versioning.branch_error')
      redirect_to collection_path(published: 0, id: draft_collection)
    else
      authorize! :branch, current_collection

      new_version = nil
      ActiveRecord::Base.transaction do
        new_version = current_collection.branch(current_user)
        new_version.save!
      end
      flash[:success] = t('txt.controllers.versioning.branched')
      redirect_to edit_collection_path(new_version, published: 0)
    end
  end

  def lock
    new_version = Iqvoc::Collection.base_class.
        by_origin(params[:origin]).
        unpublished.
        last!

    if new_version.locked?
      raise "Collection '#{new_version.origin}' is already locked."
    end

    authorize! :lock, new_version

    new_version.lock_by_user(current_user.id)
    new_version.save validate: false

    flash[:success] = t('txt.controllers.versioning.locked')
    redirect_to edit_collection_path(new_version, published: 0)
  end

  def unlock
    new_version = Iqvoc::Collection.base_class.
        by_origin(params[:origin]).
        unpublished.
        last!

    unless new_version.locked?
      raise "Collection '#{new_version.origin}' is not locked."
    end

    authorize! :unlock, new_version

    new_version.unlock
    new_version.save validate: false

    flash[:success] = t('txt.controllers.versioning.unlocked')

    redirect_to collection_path(new_version, published: 0)
  end

  def consistency_check
    collection = Iqvoc::Collection.base_class.
        by_origin(params[:origin]).
        unpublished.
        last!

    authorize! :check_consistency, collection

    if collection.publishable?
      flash[:success] = t('txt.controllers.versioning.consistency_check_success')
      redirect_to collection_path(collection, published: 0)
    else
      flash[:error] = t('txt.controllers.versioning.consistency_check_error')
      redirect_to edit_collection_path(collection, published: 0, full_consistency_check: '1')
    end
  end

  def to_review
    collection = Iqvoc::Collection.base_class.
        by_origin(params[:origin]).
        unpublished.
        last!

    authorize! :send_to_review, collection
    collection.to_review

    authorize! :unlock, collection
    collection.unlock

    collection.save!
    flash[:success] = t('txt.controllers.versioning.to_review_success')
    redirect_to collection_path(collection, published: 0)
  end
end

app/controllers/collections_controller.rb
# encoding: UTF-8

# Copyright 2011-2013 innoQ Deutschland GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class CollectionsController < ApplicationController
  def index
    authorize! :read, Iqvoc::Collection.base_class

    respond_to do |format|
      format.html do
        @top_collections = Iqvoc::Collection.base_class.with_pref_labels.published
        @top_collections = if params[:root].present?
          @top_collections.by_parent_id(params[:root])
        else
          @top_collections.tops
        end

        @top_collections.to_a.sort! { |a, b| a.pref_label.to_s <=> b.pref_label.to_s }

        ActiveRecord::Associations::Preloader.new.preload(@top_collections, { members: :target })
      end
      format.json do # For the widget and treeview
        response = if params[:root].present?
          collections = Iqvoc::Collection.base_class.with_pref_labels.published.by_parent_id(params[:root])
          collections.map do |collection|
            res = {
              id: collection.id,
              url: collection_path(id: collection, format: :html),
              name: CGI.escapeHTML(collection.pref_label.to_s),
              load_on_demand: collection.subcollections.any?
            }
            res[:additionalText] = " (#{collection.additional_info})" if collection.additional_info

            res
          end
        else
          collections = Iqvoc::Collection.base_class.with_pref_labels.published.merge(Label::Base.by_query_value("#{params[:query]}%"))
          collections.map do |c|
            collection_widget_data(c)
          end
        end
        render json: response
      end
    end
  end

  def show
    published = params[:published] == '1' || !params[:published]
    scope = Iqvoc::Collection.base_class.by_origin(params[:id])

    if published
      scope = scope.published
      @new_collection_version = Iqvoc::Collection.base_class.by_origin(params[:id]).unpublished.last
    else
      scope = scope.unpublished
    end

    @collection = scope.last!
    authorize! :read, @collection

    # When in single query mode, AR handles ALL includes to be loaded by that
    # one query. We don't want that! So let's do it manually :-)
    ActiveRecord::Associations::Preloader.new.preload(@collection,
      [:pref_labels,
        { members: { target: [:pref_labels] + Iqvoc::Collection.base_class.default_includes } }])

    respond_to do |format|
      format.html { published ? render('show_published') : render('show_unpublished') }
      format.any(:rdf, :ttl, :nt)
    end
  end

  def new
    authorize! :create, Iqvoc::Collection.base_class

    @collection = Iqvoc::Collection.base_class.new
    build_note_relations
  end

  def create
    authorize! :create, Iqvoc::Collection.base_class

    @collection = Iqvoc::Collection.base_class.new(concept_params)

    @collection.lock_by_user(current_user.id)

    if @collection.save
      flash[:success] = I18n.t('txt.controllers.collections.save.success')
      redirect_to collection_path(published: 0, id: @collection.origin)
    else
      flash.now[:error] = I18n.t('txt.controllers.collections.save.error')
      render :new
    end
  end

  def edit
    @collection = Iqvoc::Collection.base_class.by_origin(params[:id]).last!
    authorize! :update, @collection

    # When in single query mode, AR handles ALL includes to be loaded by that
    # one query. We don't want that! So let's do it manually :-)
    ActiveRecord::Associations::Preloader.new.preload(@collection, [
        :pref_labels,
        { members: { target: [:pref_labels] + Iqvoc::Concept.base_class.default_includes } }])

    build_note_relations
  end

  def update
    @collection = Iqvoc::Collection.base_class.by_origin(params[:id]).last!
    authorize! :update, @collection

    # set to_review to false if someone edits a concepts
    concept_params["to_review"] = "false"

    if @collection.update_attributes(concept_params)
      flash[:success] = I18n.t('txt.controllers.collections.save.success')
      redirect_to collection_path(@collection, published: 0)
    else
      flash.now[:error] = I18n.t('txt.controllers.collections.save.error')
      render :edit
    end
  end

  def destroy
    @collection = Iqvoc::Collection.base_class.by_origin(params[:id]).last!
    authorize! :destroy, @collection

    if @collection.destroy
      flash[:success] = I18n.t('txt.controllers.collections.destroy.success')
      redirect_to collections_path
    else
      flash.now[:error] = I18n.t('txt.controllers.collections.destroy.error')
      render action: :show
    end
  end

  private

  def concept_params
    params.require(:concept).permit!
  end

  def build_note_relations
    @collection.note_skos_definitions.build if @collection.note_skos_definitions.empty?
  end
end

app/views/collections/_collection.html.erb
<%- has_children = collection.subcollections.any? -%>
<li class="<%= has_children ? "hasChildren" : "" %>"
  id="<%= collection.id %>"
  data-has-children="<%= has_children %>"
>
  <%= link_to collection.pref_label.to_s, collection_path(id: collection) %>

  <%- if collection.additional_info -%>
    <span class="additional_info">(<%= collection.additional_info %>)</span>
  <%- end -%>
</li>

app/views/collections/_data.html.erb
<%-
# TODO: We'll need a 'collection_view_data' helper (containing the following
# "Note" stuff too).
-%>
<%#= render 'layouts/sections', :sections => ["labels"], :data => concept_view_data(collection) %>

<% Iqvoc::Concept.labeling_classes.each do |labeling_class, languages| %>
    <%= render labeling_class.partial_name(collection), klass: labeling_class, concept: collection, available_languages: languages || Iqvoc.available_languages %>
<% end %>

<div class="relation panel">
  <h2><%= Note::SKOS::Definition.model_name.human(:count => 2) %></h2>
  <ul>
    <% collection.note_skos_definitions.each do |definition| %>
      <li><%= definition.value %> (<%= definition.language %>)</li>
    <% end %>
  </ul>
</div>

<div class="relation panel">
  <h2>
    <%= Iqvoc::Concept.base_class.model_name.human(:count => 2) %>
    <% if can?(:update, Iqvoc::Concept.base_class)%>
      <small>
        (<%= collection.concepts.size %>)
      </small>
    <% end %>
  </h2>
  <div class="relation-body">
    <ul>
      <%- collection.concepts.sort {|a, b| a.pref_label.to_s <=> b.pref_label.to_s }.each do |concept| -%>
        <%- if concept.published? || (!concept.published_version_id && can?(:update, concept)) -%>
          <li><%= render concept.class.inline_partial_name, :concept => concept %></li>
        <%- end -%>
      <%- end -%>
    </ul>
  </div>
</div>

<div class="relation panel">
  <h2>
    <%= Iqvoc::Collection.base_class.model_name.human(:count => 2) %>
    <% if can?(:update, Iqvoc::Collection.base_class)%>
    <small>
      (<%= collection.subcollections.size %>)
    </small>
  <% end %>
  </h2>
  <ul class="hybrid-treeview" data-url="<%= collections_path(:format => :json) %>">
    <%= render :partial => 'collection', :collection => collection.subcollections.sort {|a, b| a.pref_label <=> b.pref_label } %>
  </ul>
</div>

app/views/collections/_form.html.erb
<%-
# TODO: Change Concept.labeling_classes to Collection.labeling_classes (in model
# too). If those two settings differ (e.g. in spez) don't forget to add
# migrations to update existing data.
-%>

<%= bootstrap_form_for collection, :as => :concept, :url => collection.new_record? ? collections_path : collection_path(collection, :published => 0), :layout => :horizontal, :label_col => 'col-sm-3', :control_col => 'col-sm-9' do |f| %>
<fieldset>
  <legend><%= t 'txt.views.layouts.sections.labels' %></legend>
  <% if not Iqvoc.const_defined?(:SKOSXL) %>
    <p><%= t 'txt.common.hint_csv_input' %></p>
  <% end %>
    <%- Iqvoc::Concept.labeling_classes.each do |labeling_class, languages| -%>
      <%- languages.each do |language| -%>
        <%= render labeling_class.edit_partial_name(@collection), :f => f,
          :concept => @collection, :klass => labeling_class, :language => language %>
      <%- end -%>
    <%- end -%>
</fieldset>

<% Iqvoc::Collection.note_classes.each do |klass| %>
  <%= render klass.edit_partial_name(@collection), :owner_klass => @collection, :assoc_klass => klass, :f => f %>
<% end %>

<fieldset>
  <legend><%= Iqvoc::Concept.base_class.model_name.human(:count => 2) %></legend>
  <%= f.form_group :inline_member_concept_origins, :label => {:text => t('txt.common.type_to_search')} do %>
    <%= text_field_tag "concept[inline_member_concept_origins]", @collection.inline_member_concept_origins.join(InlineDataHelper::JOINER),
      :class => "entity_select",
      :"data-query-url" => concepts_path(:format => :json),
      :"data-entity-uri" => concept_path(:id => "{id}"),
      :"data-entities" => @collection.inline_member_concepts.
      map { |c| concept_widget_data(c) }.to_json %>
  <% end %>
</fieldset>

<fieldset>
  <legend><%= Iqvoc::Collection.base_class.model_name.human(:count => 2) %></legend>
  <%= f.form_group :inline_member_concept_origins, :label => {:text => t('txt.common.type_to_search')} do %>
    <%= text_field_tag "concept[inline_member_collection_origins]", @collection.inline_member_collection_origins.join(InlineDataHelper::JOINER),
      :class => "entity_select",
      :"data-query-url" => collections_path(:format => :json),
      :"data-entity-uri" => collection_path(:id => "{id}"),
      :"data-exclude" => @collection.origin,
      :"data-entities" => @collection.inline_member_collections.
      map { |c| collection_widget_data(c) }.to_json %>
  <% end %>
</fieldset>

<hr />
<div class="mb-5">
  <%= f.submit t("txt.common.save"), :class => "btn btn-primary" %>
  <%= link_to t("txt.common.cancel"), collection.new_record? ? dashboard_path : collection_path(collection, :published => 0), :class => "btn btn-outline-secondary" %>
</div>

<% end %>

app/views/collections/_header.html.erb
<%= concept_header collection %>

<%= content_for :head do -%>
  <link href="<%= rdf_url(collection.origin, :format => :ttl, :lang => nil) %>" type="text/turtle" rel="alternate" title=""/>
  <link href="<%= rdf_url(collection.origin, :format => :rdf, :lang => nil) %>" type="application/rdf+xml" rel="alternate" title=""/>
<% end -%>

app/views/collections/_sidebar.html.erb
<%= sidebar do %>
  <% if defined?(collection) %>
    <%= sidebar_header t('txt.common.representations') %>
    <%= sidebar_item :icon => 'share', :text => 'HTML', :path => collection_url(collection.origin, :format => :html) %>
    <%= sidebar_item :icon => 'share', :text => 'RDF/XML', :path => rdf_url(collection.origin, :format => :rdf, :lang => nil), :id => 'rdf_link_xml' %>
    <%= sidebar_item :icon => 'share', :text => 'RDF/Turtle', :path => rdf_url(collection.origin, :format => :ttl, :lang => nil), :id => 'rdf_link_ttl' %>
    <%= sidebar_item :icon => 'share', :text => 'RDF/NTriples', :path => rdf_url(collection.origin, :format => :nt, :lang => nil), :id => 'rdf_link_nt' %>
  <% end %>
<% end %>

<%= sidebar do %>
  <% if defined?(collection) || can?(:create, Iqvoc::Collection.base_class) %>
    <%= sidebar_header 'Links' %>
  <% end %>
  <% if defined?(collection) %>
    <%= sidebar_item :icon => 'link', :text => t('txt.models.collection.uri'), :path => rdf_url(collection.origin, :format => nil, :lang => nil) %>
  <% end %>
  <%= sidebar_item :icon => :edit, :text => t("txt.views.collections.new"), :path => new_collection_path,
    :perms => [:create, Iqvoc::Collection.base_class] %>
<% end %>

app/views/collections/edit.html.erb
<%= render 'header', :collection => @collection %>
<%= error_messages_for @collection %>

<%= render 'form', :collection => @collection %>
<%= render 'sidebar', :collection => @collection %>

app/views/collections/index.html.erb
<%= page_header :title => Iqvoc::Collection.base_class.model_name.human(:count => 2) %>

<ul class="hybrid-treeview" data-url="<%= collections_path(:format => :json) %>">
  <%= render :partial => 'collection', :collection => @top_collections %>
</ul>

<%= render 'sidebar' %>

app/views/collections/new.html.erb
<%= page_header :title => t('txt.views.collections.new') %>

<%= error_messages_for @collection %>

<%= render 'form', :collection => @collection %>
<%= render 'sidebar' %>

app/views/collections/show_published.html.erb
<%= render 'header', :collection => @collection %>
<%= render 'sidebar', :collection => @collection %>

<% if @new_collection_version.blank? && can?(:branch, @collection) %>
    <div class="editing_versioning_toolbar">
      <%= button_to t("txt.views.versioning.versioning_mode"),
        collection_versions_branch_path(:origin => @collection.origin), :class => "btn btn-outline-secondary" %>
    </div>
<% elsif can?(:read, @new_collection_version) %>
    <div class="editing_versioning_toolbar">
      <%= link_to t("txt.views.versioning.preview_new_version"),
        collection_path(:published => 0, :id => @new_collection_version), :class => 'btn btn-outline-secondary' %>
    </div>
<% end %>

<%= render 'data', :collection => @collection %>

app/views/collections/show_unpublished.html.erb
<%= render 'header', :collection => @collection %>
<%= render 'sidebar', :collection => @collection %>

<%= alert :info, :header => t('txt.common.unpublished_version') + "." do %>
  <%= t("txt.views.versioning.current_revision", :rev => @collection.rev) %>
  <% if @collection.locked? %>
    <%= t("txt.views.versioning.in_ongoing_editing_by", :user => @collection.locking_user.name) %>
  <% end %>
<% end %>

<div class="editing_versioning_toolbar">
  <% if can?(:merge, @collection) %>
    <%= button_to t("txt.views.versioning.publishing"),
      collection_versions_merge_path(:origin => @collection.origin), :class => 'btn btn-primary' %>
  <% end %>

  <% if can?(:check_consistency, @collection) %>
    <%= button_to t("txt.views.versioning.consistency_check"),
      collection_versions_consistency_check_path(:origin => @collection.origin), :class => 'btn btn-outline-secondary', :method => :get %>
  <% end %>

  <% if can?(:send_to_review, @collection) %>
    <%= button_to t("txt.common.to_review"),
      collection_versions_to_review_path(:origin => @collection.origin), :class => 'btn btn-outline-secondary' %>
  <% end %>

  <% if @collection.locked? %>
    <%= button_to t("txt.views.versioning.unlock"),
      collection_versions_unlock_path(:origin => @collection.origin), :class => 'btn btn-outline-secondary' if can?(:unlock, @collection) %>
    <%= link_to t("txt.views.versioning.edit_mode"),
      edit_collection_path(:published => 0, :id => @collection.origin),
        :class => 'btn btn-outline-secondary' if can?(:update, @collection) %>
    <% else %>
      <%= button_to t("txt.views.versioning.to_edit_mode"),
        collection_versions_lock_path(:origin => @collection.origin), :class => 'btn btn-outline-secondary' if can?(:lock, @collection) %>
  <% end %>

  <% if can?(:destroy, @collection) %>
    <%= button_to delete_button_text(@collection),
        collection_path(:published => 0, :id => @collection.origin),
        :method => :delete,
        :class => 'btn btn-danger',
        :data => { :confirm => I18n.t("txt.views.versioning.delete_confirm") } if can?(:destroy, @collection) %>
  <% end %>
</div>

<%= render 'data', :collection => @collection %>