config/routes.rb
# encoding: UTF-8

# Copyright 2011-2013 innoQ Deutschland GmbH
#
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Rails.application.routes.draw do
  apipie

  scope ':lang', constraints: Iqvoc.routing_constraint do
    Iqvoc.localized_routes.each do |hook|
      hook.call(self)
      ActiveSupport::Deprecation.warn <<-EOF
        Adding routes via `Iqvoc.localized_routes` is deprecated and will
        be removed in iQvoc 4.5.
      EOF
    end

    resource  :user_session, only: [:new, :create, :destroy]
    resources :users, except: [:show]
    resources :concepts do
      member do
        get 'glance'
      end
    end
    resources :collections
    resources :imports, only: [:index, :show, :create]
    resources :exports, only: [:index, :show, :create] do
      get 'download'
    end

    get 'scheme' => 'concepts/scheme#show', as: 'scheme'
    get 'scheme/edit' => 'concepts/scheme#edit', as: 'edit_scheme'
    patch 'scheme' => 'concepts/scheme#update'

    get 'hierarchy' => 'hierarchy#index'
    get 'hierarchy/:root' => 'hierarchy#show'

    get 'triplestore_sync' => 'triplestore_sync#index'
    post 'triplestore_sync' => 'triplestore_sync#sync'

    post 'concepts/:origin/branch'      => 'concepts/versions#branch',    as: 'concept_versions_branch'
    post 'concepts/:origin/merge'       => 'concepts/versions#merge',     as: 'concept_versions_merge'
    post 'concepts/:origin/lock'        => 'concepts/versions#lock',      as: 'concept_versions_lock'
    post 'concepts/:origin/unlock'      => 'concepts/versions#unlock',    as: 'concept_versions_unlock'
    post 'concepts/:origin/to_review'   => 'concepts/versions#to_review', as: 'concept_versions_to_review'
    get 'concepts/:origin/consistency_check' => 'concepts/versions#consistency_check', as: 'concept_versions_consistency_check'

    patch 'concepts/:origin/move'        => 'concepts_movement#move',     as: 'move_concept'

    post 'collections/:origin/branch'      => 'collections/versions#branch',    as: 'collection_versions_branch'
    post 'collections/:origin/merge'       => 'collections/versions#merge',     as: 'collection_versions_merge'
    post 'collections/:origin/lock'        => 'collections/versions#lock',      as: 'collection_versions_lock'
    post 'collections/:origin/unlock'      => 'collections/versions#unlock',    as: 'collection_versions_unlock'
    post 'collections/:origin/to_review'   => 'collections/versions#to_review', as: 'collection_versions_to_review'
    get 'collections/:origin/consistency_check' => 'collections/versions#consistency_check', as: 'collection_versions_consistency_check'

    get 'alphabetical_concepts(/:prefix)' => 'concepts/alphabetical#index', as: 'alphabetical_concepts'
    get 'untranslated_concepts/:prefix'   => 'concepts/untranslated#index', as: 'untranslated_concepts'
    get 'hierarchical_concepts' => 'concepts/hierarchical#index', as: 'hierarchical_concepts'
    get 'expired_concepts' => 'concepts/expired#index', as: 'expired_concepts'

    get 'dashboard' => 'dashboard#concept_index', as: 'dashboard'
    get 'dashboard_glance' => 'dashboard#glance', as: 'dashboard_glance'
    get 'collection_dashboard' => 'dashboard#collection_index', as: 'collection_dashboard'
    match 'dashboard/reset' => 'dashboard#reset', as: 'reset', via: [:get, :post]

    get 'config' => 'instance_configuration#index', as: 'instance_configuration'
    patch 'config' => 'instance_configuration#update'

    get 'search' => 'search_results#index', as: 'search'

    get 'help' => 'pages#help', as: 'help'
    get 'version' => 'pages#version', as: 'version'
    get 'components' => 'pages#components', as: 'components'

    get '/' => 'frontpage#index', as: 'localized_root'
    match '*unmatched', to: 'errors#not_found', via: :all
  end

  patch ':origin/add_match' => 'reverse_matches#add_match', as: 'add_match'
  patch ':origin/remove_match' => 'reverse_matches#remove_match', as: 'remove_match'

  get 'remote_labels' => 'remote_labels#show', as: 'remote_label'
  get 'schema' => redirect('/'), as: 'schema'
  get 'dataset' => 'rdf#dataset', as: 'rdf_dataset'
  get 'scheme' => 'concepts/scheme#show', as: 'rdf_scheme'
  get 'search' => 'search_results#index', as: 'rdf_search'
  get 'hierarchy' => 'hierarchy#index'
  get 'hierarchy/:root' => 'hierarchy#show'

  get ':id' => 'rdf#show', as: 'rdf'

  match '*unmatched', to: 'errors#not_found', via: :all

  root to: 'frontpage#index', format: nil
end

app/models/concept/base.rb
# encoding: UTF-8

# Copyright 2011-2013 innoQ Deutschland GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class Concept::Base < ApplicationRecord
  attr_accessor :reverse_match_service
  self.table_name = 'concepts'

  class_attribute :default_includes
  self.default_includes = []

  class_attribute :rdf_namespace, :rdf_class
  self.rdf_namespace = nil
  self.rdf_class = nil

  Iqvoc::Concept.include_modules.each do |mod|
    include mod
  end

  include Versioning
  include Concept::Validations
  include FirstLevelObjectValidations
  include FirstLevelObjectScopes

  # ********** Hooks

  after_initialize do |concept|
    if concept.origin.blank?
      concept.origin = Origin.new.to_s
    end
  end

  before_validation do |concept|
    # Handle save or destruction of inline relations (relations or labelings)
    # for use with widgets etc.

    # Inline assigned SKOS::Labels
    # @labelings_by_text # => {'relation_name' => {'lang' => 'label1, label2, ...'}}
    (@labelings_by_text ||= {}).each do |relation_name, lang_values|
      relation_name = relation_name.to_s
      reflection = self.class.reflections.stringify_keys[relation_name]
      labeling_class = reflection && reflection.class_name && reflection.class_name.constantize
      if labeling_class && labeling_class < Labeling::Base
        self.send(relation_name).destroy_all
        lang_values = { nil => lang_values.first } if lang_values.is_a?(Array) # For language = nil: <input name=bla[labeling_class][]> => Results in an Array! -- XXX: obsolete/dupe (cf `labelings_by_text=`)?
        lang_values.each do |lang, inline_values|
          lang = nil if lang.to_s == 'none'
          InlineDataHelper.parse_inline_values(inline_values).each do |value|
            value.squish!
            unless value.blank?
              self.send(relation_name).build(target: labeling_class.label_class.new(value: value, language: lang))
            end
          end
        end
      end
    end
  end

  after_save do |concept|
    # Generate a origin if none was given yet
    if concept.origin.blank?
      raise 'Concept::Base#after_save (generate origin): Unable to set the origin by id!' unless concept.id
      concept.reload
      concept.origin = sprintf('_%08d', concept.id)
      concept.save! # On exception the complete save transaction will be rolled back
    end

    # Process inline relations
    #
    # NB: rankable relations' target origins may include an embedded rank,
    # delimited by a colon
    #
    # Examples:
    # regular:  {'relation_name' => ['origin1', 'origin2']}
    # rankable: {'relation_name' => ['origin1:100', 'origin2:90']}
    (@concept_relations_by_id ||= {}).each do |relation_name, new_origins|
      # Split comma-separated origins and clean up parameter strings
      new_origins = new_origins.split(InlineDataHelper::SPLITTER).map(&:squish)

      # Extract embedded ranks (if any) from origin strings (e.g. "origin1:100")
      # => { 'origin1' => nil, 'origin2' => 90 }
      new_origins = new_origins.each_with_object({}) do |e, hsh|
        key, value = e.split(':') # NB: defaults to nil if no rank is provided
        hsh[key] = value
      end

      existing_origins = concept.send(relation_name).map { |r| r.target.origin }.uniq

      # Destroy elements of the given concept relation
      concept.send(relation_name).by_target_origin(existing_origins).each do |relation|
        concept.send(relation_name).destroy_with_reverse_relation(relation.target)
      end

      # Rebuild concept relations
      # This is necessary because changing the rank of an already assigned relation
      # would otherwise be ignored.
      Concept::Base.by_origin(new_origins.keys).each do |c|
        concept.send(relation_name).create_with_reverse_relation(c, rank: new_origins[c.origin])
      end
    end

    # Process assigned collections
    if @assigned_collection_origins
      transaction do
        collections.destroy_all

        # Rebuild collection relations
        @assigned_collection_origins.each do |origin|
          collection = Iqvoc::Collection.base_class.by_origin(origin).published.first
          if collection
            Iqvoc::Collection.member_class.create! do |m|
              m.collection = collection
              m.target = concept
            end
          end
        end
      end
    end

    if (@inline_matches ||= {}).any?
      @inline_matches.each do |match_class, urls|
        # temp array to check existing match-urls
        # we cannot use @inline_matches (call by reference)
        urls_copy = urls.dup

        # destroy old relations
        self.send(match_class.to_relation_name).each do |match|
          if (urls_copy.include?(match.value))
            urls_copy.delete(match.value) # We're done with that one
          else
            self.send(match_class.to_relation_name).destroy(match.id) # User deleted this one

            if self.reverse_match_service.present? && federation_match?(match.value)
              job = self.reverse_match_service.build_job(:remove_match, self, match.value, match_class)
              self.reverse_match_service.add(job)
            end

          end
        end

        # create new match relations
        urls_copy.each do |url|
          self.send(match_class.to_relation_name) << match_class.constantize.new(value: url)

          if self.reverse_match_service.present? && federation_match?(url)
            job = self.reverse_match_service.build_job(:add_match, self, url, match_class)
            self.reverse_match_service.add(job)
          end

        end
      end
    end

  end

  # ********** "Static"/unconfigureable relations

  @nested_relations = [] # Will be marked as nested attributes later

  has_many :relations,
           foreign_key: 'owner_id',
           class_name: 'Concept::Relation::Base',
           dependent: :destroy,
           inverse_of: :owner

  has_many :related_concepts,
           through: :relations,
           source: :target

  has_many :referenced_relations,
           foreign_key: 'target_id',
           class_name: 'Concept::Relation::Base',
           dependent: :destroy,
           inverse_of: :target
  include_to_deep_cloning(:relations, :referenced_relations)

  has_many :labelings,
           foreign_key: 'owner_id',
           class_name: 'Labeling::Base',
           dependent: :destroy,
           inverse_of: :owner

  has_many :labels, -> { order(:value) },
           through: :labelings,
           source: :target
  # Deep cloning has to be done in specific relations. S. pref_labels etc

  has_many :notes,
           class_name: 'Note::Base',
           as: :owner,
           dependent: :destroy,
           inverse_of: :owner
  include_to_deep_cloning({ notes: :annotations })

  has_many :matches,
           foreign_key: 'concept_id',
           class_name: 'Match::Base',
           dependent: :destroy,
           inverse_of: :concept
  include_to_deep_cloning(:matches)

  has_many :collection_members,
           foreign_key: 'target_id',
           class_name: 'Collection::Member::Base',
           dependent: :destroy,
           inverse_of: :target

  has_many :collections,
           through: :collection_members,
           class_name: Iqvoc::Collection.base_class_name
  include_to_deep_cloning(:collection_members)

  has_many :notations,
           class_name: 'Notation::Base',
           foreign_key: 'concept_id',
           dependent: :destroy,
           inverse_of: :concept
  include_to_deep_cloning :notations

  @nested_relations << :notations

  # ************** "Dynamic"/configureable relations

  # *** Concept2Concept relations

  # Broader
  # FIXME: Actually this is not needed anymore.
  # BUT: the include in scope :tops doesn't work with
  # 'Iqvoc::Concept.broader_relation_class_name'!?!?! (Rails Bug????)
  has_many :broader_relations,
    foreign_key: :owner_id,
    class_name: Iqvoc::Concept.broader_relation_class_name,
    extend: Concept::Relation::ReverseRelationExtension,
    inverse_of: :owner

  # Narrower
  # FIXME: Actually this is not needed anymore.
  # BUT: the include in scope :tops doesn't work with
  # 'Iqvoc::Concept.broader_relation_class_name'!?!?! (Rails Bug????)
  has_many :narrower_relations,
    foreign_key: :owner_id,
    class_name: Iqvoc::Concept.broader_relation_class.narrower_class.name,
    extend: Concept::Relation::ReverseRelationExtension,
    inverse_of: :owner

  # Relations
  # e.g. 'concept_relation_skos_relateds'
  # Attention: Iqvoc::Concept.relation_class_names loads the Concept::Relation::*
  # classes!
  Iqvoc::Concept.relation_class_names.each do |relation_class_name|
    has_many relation_class_name.to_relation_name,
      foreign_key: :owner_id,
      class_name: relation_class_name,
      extend: Concept::Relation::ReverseRelationExtension,
      inverse_of: :owner
  end

  # *** Labels/Labelings

  has_many :pref_labelings,
    foreign_key: 'owner_id',
    class_name: Iqvoc::Concept.pref_labeling_class_name,
    inverse_of: :owner

  has_many :pref_labels,
    -> { order(:value) },
    through: :pref_labelings,
    source: :target

  has_many :alt_labelings,
    foreign_key: 'owner_id',
    class_name: Iqvoc::Concept.alt_labeling_class_name,
    inverse_of: :owner

  has_many :alt_labels,
    -> { order(:value) },
    through: :alt_labelings,
    source: :target

  Iqvoc::Concept.labeling_class_names.each do |labeling_class_name, languages|

app/models/concept/inline_notes_handling.rb
# encoding: UTF-8

# Copyright 2011 innoQ Deutschland GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module Concept
  module InlineNotesHandling
    extend ActiveSupport::Concern

    included do
      before_validation :process_inline_notes
      after_save :persist_notes

      attr_writer :inline_notes
    end

    # returns a hash of hashes, first-level key being the rdf type, second level key being the note ID
    # ex: inline_notes = {'skos:scopeNote' => {'1' => {'language' => 'en', 'value' => 'Foo', '_delete' => '0'}, ...}, ...}
    def inline_notes(reload = false)
      if reload
        @inline_notes = load_inline_notes
      else
        @inline_notes ||= load_inline_notes
      end
      @inline_notes.each do |key, values|
        if values.is_a? Array
          @inline_notes[key] = {'0' => values.first} # HACK
        end
      end
    end

    protected

    def persist_notes
      self.notes.each &:save
    end

    def load_inline_notes
      Hash.new.with_indifferent_access.tap do |n|
        self.notes.each do |note|
          n[note.rdf_internal_name] ||= Hash.new.with_indifferent_access
          n[note.rdf_internal_name][note.id.to_s] = note.attributes.with_indifferent_access
        end
      end
    end

    def process_inline_notes
      self.inline_notes.each do |rdf_type, notes_attrs|
        self.notes.for_rdf_class(rdf_type).each do |note|
          self.notes.destroy_later(note)
        end

        notes_attrs.each_pair do |id, attrs|
          lang = attrs[:language].to_s == 'none' ? nil : attrs[:language]
          unless attrs[:value].blank? or attrs[:_destroy].to_s == '1'
            tokens = {:ObjectLangstringLanguage => lang, :ObjectLangstringString => attrs[:value], :Predicate => rdf_type}
            self.notes.build_from_parsed_tokens(tokens, :subject_instance => self)
            # TODO: handle annotations and other attributes
          end
        end
      end
    end

  end
end

app/models/concept/labeling_subtype_extensions.rb
# encoding: UTF-8

module Concept
  module LabelingSubtypeExtensions

    def each_configured_class(&block)
      Iqvoc::Concept.labeling_class_names.each do |name, languages|
        yield name.constantize
      end
    end

  end
end

app/views/concepts/_form.html.erb
<%= bootstrap_form_for concept,
    :as => :concept,
    :url => concept.new_record? ? concepts_path : concept_path(:published => 0, :id => concept),
    :layout => :horizontal do |f| %>

  <!-- Base data -->
  <fieldset>
    <legend><%= t('txt.common.attributes') %></legend>
    <%= f.text_field :follow_up, :class => 'datepicker' %>
    <%= f.text_field :expired_at, :class => 'datepicker' %>

    <%- Iqvoc::Concept.additional_association_classes.keys.each do |assoc_class| -%>
      <%= render assoc_class.edit_partial_name(concept),
        :concept => concept, :klass => assoc_class, :f => f %>
    <%- end -%>
  </fieldset>
  <!-- / Base data -->

  <!-- Labelings -->
  <fieldset>
    <legend><%= Labeling::Base.model_name.human(:count => 2) %></legend>
    <% unless Iqvoc.const_defined?(:SKOSXL) %>
      <p><%= t 'txt.common.hint_csv_input' %></p>
    <% end %>
    <%- Iqvoc::Concept.labeling_classes.each do |labeling_class, languages| -%>
      <%- languages.each do |language| -%>
        <%= render labeling_class.edit_partial_name(concept), :f => f,
          :concept => concept, :klass => labeling_class, :language => language %>
      <%- end -%>
    <%- end -%>
  </fieldset>
  <!-- / Labelings -->

  <!-- Concept relations -->
  <fieldset>
    <legend><%= Concept::Relation::Base.model_name.human(:count => 2) %></legend>
    <% unless Iqvoc::Concept.broader_relation_class.edit_partial_name(concept).nil? %>
      <%- if Iqvoc::Concept.broader_relation_class.narrower_editable -%>
        <%= render Iqvoc::Concept.broader_relation_class.narrower_class.edit_partial_name(concept),
          :concept => concept, :klass => Iqvoc::Concept.broader_relation_class.narrower_class, :f => f %>
      <%- end -%>

      <%= f.form_group :top_term do %>
        <%= f.check_box :top_term,
          :class => ("exclusive" if Iqvoc::Concept.broader_relation_class.singular?) %>
      <% end %>

      <%= render Iqvoc::Concept.broader_relation_class.edit_partial_name(concept),
        :concept => concept, :klass => Iqvoc::Concept.broader_relation_class, :f => f %>
    <% end %>

    <%- Iqvoc::Concept.further_relation_classes.each do |relation_class| -%>
      <%= render relation_class.edit_partial_name(concept),
        :concept => concept, :klass => relation_class, :f => f %>
    <%- end -%>
  </fieldset>
  <!-- / Concept relations -->

  <!-- Collections -->
  <fieldset>
    <legend><%= Iqvoc::Collection.base_class.model_name.human(:count => 2) %></legend>
    <%= f.form_group :assigned_collection_origins, :label => {:text => t('txt.common.type_to_search')} do %>
      <%= text_field_tag "concept[assigned_collection_origins]",
        concept.assigned_collection_origins.join(InlineDataHelper::JOINER),
        :class => "entity_select",
        :"data-query-url" => collections_path(:format => :json),
        :"data-entity-uri" => collection_path(:id => "{id}"),
        :"data-entities" => concept.collections.map { |c| collection_widget_data(c) }.to_json %>
    <% end %>
  </fieldset>
  <!-- /Collection -->

  <!-- Notes ohne Change Note class -->
  <% Iqvoc::Concept.note_classes.reject { |n| n == Iqvoc.change_note_class  }.each do |note_class| %>
    <% unless note_class.edit_partial_name(concept).nil? %>
      <%= render note_class.edit_partial_name(concept), :owner_klass => concept, :assoc_klass => note_class, :f => f %>
    <% end %>
  <% end %>
  <!-- / Notes -->

  <!-- Matches -->
  <fieldset class="matches" data-datasets="<%= @datasets %>" data-remote-proxy-url="<%= alphabetical_concepts_path %>" data-translation-other="<%= t('txt.common.other') %>" data-no-results-msg="<%= t('txt.views.search_results.no_results') %>">
    <legend><%= Match::Base.model_name.human(:count => 2) %></legend>
    <% Iqvoc::Concept.match_classes.each do |match_class| %>
      <%= render match_class.edit_partial_name(concept), :owner_klass => concept, :assoc_klass => match_class, :f => f %>
    <% end %>
  </fieldset>
  <!-- / Matches -->

  <!-- Notations -->
  <% Iqvoc::Concept.notation_classes.each do |notation_class| %>
    <%= render notation_class.edit_partial_name(concept), :owner_klass => concept, :assoc_klass => notation_class, :f => f %>
  <% end %>
  <!-- / Notations -->

  <!-- Change Note class -->
  <% note_class = Iqvoc.change_note_class %>
  <% unless note_class.edit_partial_name(concept).nil? %>
    <%= render note_class.edit_partial_name(concept), :owner_klass => concept, :assoc_klass => note_class, :f => f %>
  <% end %>
  <!-- / Change Note class -->

  <hr />

  <div class="mb-5">
    <%= f.submit t("txt.common.save"), :class => "btn btn-primary" %>
    <%= link_to t("txt.common.cancel"), concept.new_record? ? dashboard_path : concept_path(:published => 0, :id => concept), :class => "btn btn-outline-secondary" %>
  </div>

<% end %>

app/views/concepts/_header.html.erb
<% published_param = concept.published? ? nil : 0 %>
<%= content_for :head do -%>
  <link href="<%= rdf_url(concept.origin, :format => :ttl, :published => published_param, :lang => nil) %>" type="text/turtle" rel="alternate" title=""/>
  <link href="<%= rdf_url(concept.origin, :format => :rdf, :published => published_param, :lang => nil) %>" type="application/rdf+xml" rel="alternate" title=""/>
  <link href="<%= concept_path(concept, :format => :json, :published => published_param) %>" type="application/json" rel="alternate"/>
<% end -%>

<%= concept_header concept %>

app/views/concepts/_sidebar.html.erb
<%- published_param = concept.published? ? nil : "0" -%>

<%= sidebar do %>
  <%= sidebar_header t('txt.common.representations') %>
  <%= sidebar_item :icon => 'share', :text => 'HTML', :path => rdf_url(concept.origin, :format => :html, :published => published_param, :lang => nil) %>
  <%= sidebar_item :icon => 'share', :text => 'RDF/XML', :path => rdf_url(concept.origin, :format => :rdf, :published => published_param, :lang => nil) %>
  <%= sidebar_item :icon => 'share', :text => 'RDF/Turtle', :path => rdf_url(concept.origin, :format => :ttl, :published => published_param, :lang => nil) %>
  <%= sidebar_header 'Links' %>
  <%= sidebar_item :icon => :edit, :text => t("txt.views.concepts.new", :concept_class_name => Iqvoc::Concept.base_class.model_name.human), :path => new_concept_path,
    :perms => [:create, Iqvoc::Concept.base_class], :active => params[:action] == 'new' %>
<% end %>

app/views/concepts/_summary.html.erb
<div class="concept-summary row">
  <% if @view.definition %>
  <blockquote class="col-md-8">
    <%= auto_link(@view.definition, :html => { :target => '_blank' }) %>
  </blockquote>
  <% end %>

  <div class="col-md-4">
    <% if @view.collections %>
    <h3>Collections</h3> <%# FIXME: hard-coded %>
    <ul class="collections list-group">
      <% @view.collections.each do |link| %>
      <li class="list-group-item"><%= link_to link.caption, link.uri %></li>
      <% end %>
    </ul>
    <% end %>

    <% if @view.related %>
    <h3>Related Concepts</h3> <%# FIXME: hard-coded %>
    <ul class="related list-group">
      <% @view.related.each do |link| %>
      <li class="list-group-item"><%= link_to link.caption, link.uri %></li>
      <% end %>
    </ul>
    <% end %>
  </div>
</div>

app/views/concepts/edit.html.erb
<%= render 'header', :concept => @concept %>
<%= render 'concepts/sidebars/singular', :concept => @concept %>

<%= error_messages_for @concept %>

<%= render 'concepts/notifications/referenced_concepts',
  :association_objects_in_editing_mode => @association_objects_in_editing_mode %>

<%= render 'form', :concept => @concept %>

app/views/concepts/glance.html.erb
<!-- Modal -->
<div class="modal-dialog modal-lg concept-teaser-dialog" role="document">
  <div class="modal-content concept-teaser-content">
    <div class="modal-header concept-teaser-header">
      <h1 class="modal-title" id="concept-teaser-title"><%= @concept.pref_label %></h1>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only"><%= t('txt.views.concepts.teaser.close') %></span>
      </button>
    </div>
    <div class="modal-body concept-teaser-body">
      <% if @view.no_content? %>
      <div class="alert alert-warning" role="alert">
        <%= t('txt.views.concepts.teaser.no_content') %>
      </div>
      <% end %>
      <% if @view.definition %>
      <div>
        <h2><%= Note::SKOS::Definition.model_name.human %></h2>
        <p><%= @view.definition %></p>
      </div>
      <% end %>
      <% if @view.alt_labels.any? %>
      <div>
        <h2><%= Iqvoc::Concept.alt_labeling_class.model_name.human(count: 2) %></h2>
        <ul class="label-list">
          <% @view.alt_labels.each do |l| %><!--
          --><li class="label-list-item">
               <span class="label-list-item-value"><%= l.value %></span>
             </li><!--
          --><% end %>
        </ul>
      </div>
      <% end %>
      <% if @view.collections.any? %>
      <div>
        <h2><%= Iqvoc::Collection.base_class.model_name.human(count: 2) %></h2>
        <ul>
          <% @view.collections.each do |c| %>
            <li><%= link_to c.caption, c.uri %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <% if @view.related.any? %>
      <div>
        <h2><%= Iqvoc::Concept.further_relation_classes.first.try { |klass| klass.model_name.human(count: 2) } %></h2>
        <ul>
          <% @view.related.each do |c| %>
            <li><%= link_to c.caption, c.uri %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
    </div>
    <div class="modal-footer concept-teaser-footer">
      <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
      <a href="<%= concept_path(@concept) %>" class="btn btn-primary"><i class="fa fa-angle-double-right"></i> <%= t('txt.views.concepts.to_concept') %></a>
    </div>
  </div>
</div>
<!-- / Modal -->

app/views/concepts/new.html.erb
<%= page_header :title => t("txt.views.concepts.new", :concept_class_name => Iqvoc::Concept.base_class.model_name.human(:count => 1)) %>

<%= error_messages_for @concept %>
<%= render 'concepts/form', :concept => @concept %>
<%= render 'concepts/sidebars/singular' %>